"""Extend vacation request model  - add manager

Revision ID: 1f6176f2bc14
Revises: d7fc9df2556a
Create Date: 2025-05-09 21:25:11.311788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f6176f2bc14'
down_revision: Union[str, None] = 'd7fc9df2556a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_request', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key("vacation_request_manager_id_fkey", 'vacation_request', 'employee', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("vacation_request_manager_id_fkey", 'vacation_request', type_='foreignkey')
    op.drop_column('vacation_request', 'manager_id')
    # ### end Alembic commands ###
