"""Vacation Request Model

Revision ID: 25930cf0bc12
Revises: e745bc2b55b9
Create Date: 2025-04-24 13:55:38.299967

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25930cf0bc12'
down_revision: Union[str, None] = 'e745bc2b55b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_vacation_type_available_days',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('vacation_type_id', sa.Integer(), nullable=False),
    sa.Column('available_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['vacation_type_id'], ['vacation_type.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'vacation_type_id')
    )
    op.create_table('vacation_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ACCEPTED', 'REJECTED', name='vacationrequeststatus'), nullable=False),
    sa.Column('vacation_type_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacation_type_id'], ['vacation_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('employee', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_table('vacation_request')
    op.drop_table('employee_vacation_type_available_days')
    op.drop_table('vacation_type')
    # ### end Alembic commands ###
