"""Full name computed

Revision ID: 37135718d52d
Revises: aa1726d9c0fc
Create Date: 2025-06-12 12:21:34.421806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37135718d52d'
down_revision: Union[str, None] = 'aa1726d9c0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('full_name', sa.VARCHAR(), sa.Computed("first_name || ' ' || last_name", ), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'full_name')
    # ### end Alembic commands ###
