"""Job title and Department property

Revision ID: 70edb8071a4b
Revises: 04f9cb6d3e5a
Create Date: 2025-06-09 11:56:09.702082

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70edb8071a4b'
down_revision: Union[str, None] = '1f6176f2bc14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('employee', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'department')
    op.drop_column('employee', 'job_title')
    # ### end Alembic commands ###
